-- Esquema para Oracle Autonomous Database (TJHOTELS).
-- Equivalente a Hotels.sql, que es el original de SQL Server.
--
-- Se corre conectado como ADMIN desde SQL Developer Web (consola de OCI:
-- Database actions -> SQL) o con SQLcl usando el wallet.
--
-- Diferencias con SQL Server, por si comparas los dos archivos:
--   IDENTITY(1,1)          -> GENERATED BY DEFAULT AS IDENTITY
--   VARCHAR(n)             -> VARCHAR2(n)
--   BIT                    -> NUMBER(1) con CHECK (0,1)
--   DATETIME + GETDATE()   -> TIMESTAMP + SYSTIMESTAMP
--   No hay CREATE DATABASE: la base ya existe (la creamos en la consola).

CREATE TABLE Users (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR2(100),
    lastname     VARCHAR2(100),
    dateOfBirth  DATE,
    username     VARCHAR2(50),
    password     VARCHAR2(255),
    phone        VARCHAR2(20),
    status       NUMBER(1) DEFAULT 1 CHECK (status IN (0, 1))
);

CREATE TABLE Locations (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR2(100),
    description  VARCHAR2(255),
    address      VARCHAR2(255),
    lat          BINARY_DOUBLE NOT NULL,
    lng          BINARY_DOUBLE NOT NULL,
    userID       NUMBER,
    status       NUMBER(1) DEFAULT 1 CHECK (status IN (0, 1)),
    CONSTRAINT fk_locations_user FOREIGN KEY (userID) REFERENCES Users(id)
);

CREATE TABLE Favorites (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userID     NUMBER NOT NULL,
    placeID    VARCHAR2(255) NOT NULL,
    createdAt  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_favorites_user FOREIGN KEY (userID) REFERENCES Users(id),
    CONSTRAINT uq_favorites_user_place UNIQUE (userID, placeID)
);

CREATE TABLE SupportTickets (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(100) NOT NULL,
    email      VARCHAR2(255) NOT NULL,
    topic      VARCHAR2(50)  NOT NULL,
    message    VARCHAR2(2000) NOT NULL,
    userID     NUMBER,
    createdAt  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_support_user FOREIGN KEY (userID) REFERENCES Users(id)
);
